---
apiVersion: v1
kind: Secret
metadata:
  name: tsig-secret
  namespace: external-dns
type: Opaque
stringData:
  rfc2136_tsig_secret: "{{ .Values.secrets.bind9tsigKey }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: tsig-secret
  namespace: cert-manager
type: Opaque
stringData:
  rfc2136_tsig_secret: "{{ .Values.secrets.bind9tsigKey }}"

