---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: "{{ .Values.global.acmeEmailAddress }}"
    server: https://acme-v02.api.letsencrypt.org/directory 
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        rfc2136:
          nameserver: bind-primary.bind9.svc.cluster.local
          tsigKeyName: tsigkey
          tsigAlgorithm: HMACSHA512
          tsigSecretSecretRef:
            name: tsig-secret
            key: rfc2136_tsig_secret

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls
  namespace: cert-manager
spec:
  dnsNames:
    - "*.{{ .Values.global.domain }}"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: wildcard-tls
  usages:
    - digital signature
    - key encipherment


# ---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-staging
# spec:
#   acme:
#     email: "{{ .Values.global.acmeEmailAddress }}"
#     server: https://acme-staging-v02.api.letsencrypt.org/directory 
#     privateKeySecretRef:
#       name: letsencrypt-staging-account-key
#     solvers:
#     - dns01:
#         rfc2136:
#           nameserver: bind-primary.bind9.svc.cluster.local
#           tsigKeyName: tsigkey
#           tsigAlgorithm: HMACSHA512
#           tsigSecretSecretRef:
#             name: tsig-secret
#             key: rfc2136_tsig_secret 
#
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: wildcard-tls-staging
#   namespace: traefik
# spec:
#   dnsNames:
#     - "*.{{ .Values.global.externalDomainName }}"
#   issuerRef:
#     kind: ClusterIssuer
#     name: letsencrypt-staging
#   secretName: wildcard-tls-staging
#   usages:
#     - digital signature
#     - key encipherment

