{{- range .Values.ingresses }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/target: "{{ .externalDnsTarget }}"
spec:
  rules:
  - host: "{{ .host }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .service.name }}
            port:
              number: {{ .service.port }}
{{- end }}

