---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ingress-ip1
  namespace: metallb-system
spec:
  addresses: ["{{ .Values.global.ingressIP1 }}/32"]

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ingress-ip2
  namespace: metallb-system
spec:
  addresses: ["{{ .Values.global.ingressIP2 }}/32"]

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: metallb-system

