---
global:
  externalDomainName: ""
  ingressIpExternal: ""
  ingressIpInternal: ""
  
bind9:
  enabled: true
  primaryClusterIP: "10.100.0.53"
  secondaryReplicas: 4
  zone:
    refresh: 10
    retry: 10
    expire: 3600
    negativeCacheTtl: 3600
    # passed through tpl
    dnsRecords:
      - name: ns
        type: A
        value: "{{ .Values.global.ingressIpExternal }}"
      - name: traefik
        type: A
        value: "{{ .Values.global.ingressIpExternal }}"
