---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ingress-ip
  namespace: metallb
spec:
  addresses: ["{{ .Values.global.ingressIpInternal }}/32"]
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: metallb

